### ISSUE TITLE
Questions ?

### ISSUE THREAD

**Issue by gaminglnk** [illusionTBA/AniMappings#3]
**Nice work buddy,** was looking forward to get a mapping API for [Project Kimitsu](https://kimitsu.vercel.app/), 
• How can I host my own instance?
• Are there any free hosting providers?
• Is this based on MalSync API or something else?
• Can I use the default API route https://api.delusionz.xyz/ in the project ?

All these questions are for just adding a fallback method in the Project if consumet.ts fails.

**Comment by illusionTBA** [comment]
hi there
1. instructions are in README
2. yes there are like [Railway](https://railway.app). there are probably more that i dont know of but railway has all ways been good.
3. Some mappings are based on Malsync API.
4. Yes but if you have the option you should host your own.
Hope i answered all your questions. If you have future inquiries i recommend to DM me on discord @ illusions#3875
